### PR TITLE
Option to grab client IP from HTTP headers.

### PR DESCRIPTION
**Pull request by ciphermenial**
I don't really know what I am doing but I was hoping this might be close to what is required to have the ability to use Client IP accessed from HTTP headers. I have this working with CF-Connection-IP.

### CODE REVIEW

**Comment by ciphermenial** [comment]
Bump.

**Comment by LaurenceJJones** [comment]
Hey firstly let me first say thank you and sorry for how long its taken for us to comment on this PR.

So we need to take it a step further and check that the current `txn.f:src()` is a "trusted" IP, we would need to allow the user to set a list of IP within the configuration and test the current is trusted then take header. If we do not and the user does not firewall / protect the upstream they can be spoofed into believing they are receiving a valid request, but with a user controlled header.

**Comment by ciphermenial** [comment]
Yeah, I only allow connections from CloudFlare on my router. I guess this is something that would need to be mentioned in documentation.

I don't see any other way to make this bouncer work otherwise.

**Comment by LaurenceJJones** [comment]
Hey,

We been discussing this PR internally to which we decided that the bouncer should not handle this as HAPROXY should set the src_ip before hitting the lua code. We see too many vulnerabilities and additional headache if the bouncer needs to handle it.. the best way would be to configure HAproxy to set the real source IP from the trusted ip file, an example from cloudflare docs
```
  acl from_cf src -f /etc/haproxy/cf-ips/cf-ips
  http-request set-src req.hdr(CF-Connecting-IP) if from_cf
```

**Pull request closed without merging**
